import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/home.module.css'
import React, { Suspense, useEffect, useState } from "react";
import { ReactDOM } from 'react-dom'
import TestG from '@/components/test-g'
import { Canvas, useFrame } from '@react-three/fiber';
import 'tailwindcss/tailwind.css'
// import { MantineProvider } from '@mantine/core'
import _JSXStyle from 'styled-jsx/style'
import { VscMenu, VscChromeClose } from "react-icons/vsc";
import { GrMenu,GrInstagram,GrGithub,GrLanguage } from "react-icons/gr";
import { BiLogoFacebookSquare } from "react-icons/bi";
import { CgArrowRight } from "react-icons/cg";
import { VscCircleSmallFilled } from "react-icons/vsc";
import { TfiClose } from "react-icons/tfi";


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const textshadow={
    textShadow: 'rgba(0, 0, 0, 0.6) 1px 0 6px'
  };

  const bgc={
    background: 'rgba(217, 217, 217, 1)',
  };

  const [showNav, setNav] = useState(false)

  const [isClicked, setIsClicked] = useState(false);

  const toggleNav = () => {
    setNav(!showNav);
    setIsClicked(!isClicked);
  };

  const [isHovered, setIsHovered] = useState(false);

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      

      
        <div className="border border-black relative">
        <div className="border border-black m-1">
          <div>
      <div className="border-b border-black flex flex-row ">
        {showNav ? (
          // <div className="border border-black bg-white p-0.5 m-2 boxshadow" onClick={toggleNav}>
          <div
                className={`border border-black bg-white p-0.5 m-2 boxshadow ${isClicked ? 'transform -translate-x-0.5 -translate-y-0.5' : ''}`}
                onClick={toggleNav}
              >
            <div className="border border-black bg-white p-2">
              <TfiClose className='h-5 w-5'/>
            </div>
          </div>
        ) : (
          <div className="border border-black bg-white p-0.5 m-2" onClick={toggleNav}>
            <div className="border border-black bg-white p-2">
              <VscMenu className='h-5 w-5'/>
            </div>
          </div>
        )}
        
        <div className='grow flex flex-row content-center self-center'>
          <div className='grow text-3xl font-medium text-center'>Ellie's Work</div>
        </div>
      </div>

      
      {showNav && (
        <div style={{ ...bgc, zIndex: 10 }} className='p-1 border border-black absolute top-16'>
          <div className='h-96 border border-black flex flex-col'>
            <div className='flex flex-row py-1 w-60 border border-b-zinc-700'>
              <div className='flex-none'>Project 001</div>
              <div className='flex-auto'></div>
              <CgArrowRight className='h-6 w-6 flex-none'/>
            </div>
            <div className='flex-none w-60 py-1 border border-b-zinc-700'>
              <div className='flex-none'>Project 002</div>
            </div>
            <div className='flex-none w-60 py-1 border border-b-zinc-700'>
              <div className='flex-none'>Project 003</div>
            </div>
            <div className='flex-none w-60 py-1 border border-b-zinc-700'>
              <div className='flex-none'>Project 004</div>
            </div>
            <div className='flex-none w-60 py-1 border border-b-zinc-700'>
              <div className='flex-none'>Project 005</div>
            </div>
            <div className='flex-none w-60 py-1 border border-b-zinc-700'>
              <div className='flex-none'>Project 006</div>
            </div>
            <div className='flex-auto w-60 py-1 border border-b-zinc-700'></div>
            <div className='flex-none w-60 py-1'>
              <div className='flex-none'>Login</div>
            </div>
          </div>
        </div>
      )}
    </div>
          
          
        <div className="h-dvh overflow-hidden">
          <TestG />

        </div>

        <div className='flex flex-col md:flex-row border border-t-black '>
          <div className='flex justify-center py-1 px-6 border border-b-black'>
            <div className='text-xs font-normal'>
            <p>= = = = = = = = = = = = = = = =</p>
            <p>= &thinsp;╔═╗╦  ╔═╗╔═╗╔═╗╦ ╦╦═╗╔═╗╔═╗ &thinsp;&thinsp;=</p>
            <p>= &thinsp;╠═╝║  ║╣ ╠═╣╚═╗║ ║╠╦╝║╣ ╚═╗ &thinsp;&thinsp;=</p>
            <p>= &thinsp;╩  ╩═╝╚═╝╩ ╩╚═╝╚═╝╩╚═╚═╝╚═╝ &thinsp;&thinsp;=</p>
            <p>= = = = = = = = = = = = = = = =</p>
              </div>
          </div>
          <div className='flex-auto border md:border-l-black border-b-black '>
            <div className='flex justify-center py-8'>
              <div style={textshadow} className='text-base font-light hover:font-normal'>SEARCH</div>
              <div style={textshadow} className='px-6 w-auto text-base font-light hover:font-normal'>ACCESSIBILITY</div>
              <div style={textshadow} className='text-base font-light hover:font-normal'>CONTACT</div>
            </div>
          </div>
          {/* <div className='flex-auto border md:border-l-black border-b-black'>
            <div className='flex flex-col justify-center py-6'>
            <div className='flex flex-row px-6'>
            <div className='flex-auto border border-black bg-white'></div>
            <CgArrowRight className='h-6 w-6 border border-black ml-1'/>
            </div>
            <div className='px-6 w-auto text-xs font-normal break-words place-content-center'>
              Sign your life away. Just kidding, stay connected.font-weight: 700;
              </div>
            </div>
          </div> */}
           <div className='flex-auto border md:border-l-black border-b-black'>
          <div className='flex flex-col justify-center py-6'>
            <div className='flex flex-row px-6 group'>
              {/* <div className='flex-auto border border-black bg-white'></div> */}
              <input 
                type="text" 
                className='flex-auto border border-black bg-white text-sm mb-1' 
                style={{ 
                  padding: '0.2rem', 
                  outline: 'none' 
                }} 
              />
              <CgArrowRight
                className='h-7 w-7 border border-black ml-1'
                style={{
                  boxShadow: isHovered ? '3px 3px 0px black' : 'none',
                  transform: isHovered ? 'translate(-2px, -2px)' : 'none',
                  transition: 'transform 0.2s, box-shadow 0.2s'
                }}
                onMouseEnter={() => setIsHovered(true)}
                onMouseLeave={() => setIsHovered(false)}
              />
            </div>
            <div className='px-6 w-auto text-xs font-normal break-words place-content-center'>
              Sign your life away. Just kidding, stay connected.
            </div>
          </div>
        </div>
          <div className='flex-auto border md:border-l-black border-b-black'>
            <div className='flex flex-row gap-7 justify-center px-6 py-8'>
              <GrInstagram className='h-5 w-5'/>
              <BiLogoFacebookSquare className='h-5 w-5'/>
              <GrGithub className='h-5 w-5'/>
              <GrLanguage className='h-5 w-5'/>
            </div>
          </div>
        </div>
        <div className='flex flex-col py-4'>
          <div style={textshadow} className='pl-6 w-auto text-xs font-light'>@ 2024 Front-end Exercise | Site by Ellie</div>
          <div className='flex flex-row pt-1'>
              <div style={textshadow} className='pl-6 w-auto text-xs font-light'>* Privacy Policy</div>
              <div style={textshadow} className='pl-6 w-auto text-xs font-light'>* Terms of service</div>
              </div>
              
          
        </div>
        </div>
        </div>
      {/* </main> */}
      <style global jsx>{`
      .boxshadow {
  box-shadow: 3px 3px 0px black;
}
        `} </style>
    </>
  )
}
